# Generated by Django 4.0.2 on 2022-02-01 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 1, 18, 8, 56, 551725))),
                ('body', models.CharField(max_length=10000000000000)),
            ],
        ),
    ]
